dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- name: oakary-ats-client
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.4
- name: oakary-ats-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
